-- Carga inicial do Estoque: os 65 produtos da planilha (o "Ninho Trufado c/ Morango" só existe em Bolos de Potes) de reposição de 29/09/2026,
-- com a quantidade da coluna "Estoque Atual". Roda depois da 0010. Produto já existente
-- (mesmo id) não é tocado — a equipe pode ter mexido na quantidade.
insert into produto (id, nome, categoria, quantidade) values
  ('p-frutas-banoffinha', 'Banoffinha', 'Frutas', 0),
  ('p-frutas-bombom-de-morango', 'Bombom de Morango', 'Frutas', 0),
  ('p-frutas-bombom-de-uva', 'Bombom de Uva', 'Frutas', 0),
  ('p-frutas-folhata-com-morango', 'Folhata com Morango', 'Frutas', 0),
  ('p-frutas-morango-com-nata', 'Morango com Nata', 'Frutas', 0),
  ('p-frutas-bombom-morango-pistache-cravejado', 'Bombom morango pistache cravejado', 'Frutas', 0),
  ('p-frutas-bombom-de-morango-rosa-cravejado', 'Bombom de morango rosa cravejado', 'Frutas', 0),
  ('p-caseirinhos-caseirinho-cenoura', 'Caseirinho Cenoura', 'Caseirinhos', 40),
  ('p-caseirinhos-caseirinho-nutelinho', 'Caseirinho Nutelinho', 'Caseirinhos', 30),
  ('p-brownies-brownie-duo', 'Brownie duo', 'Brownies', 0),
  ('p-copinhos-copo-cravejado', 'Copo cravejado', 'Copinhos', 0),
  ('p-copinhos-bueno', 'Bueno', 'Copinhos', 7),
  ('p-copinhos-ferrero', 'Ferrero', 'Copinhos', 36),
  ('p-copinhos-kinder-mix', 'Kinder Mix', 'Copinhos', 37),
  ('p-copinhos-ouro-branco', 'Ouro Branco', 'Copinhos', 58),
  ('p-copinhos-rafaello', 'Rafaello', 'Copinhos', 65),
  ('p-copinhos-bolo-pudim', 'Bolo Pudim', 'Copinhos', 1),
  ('p-bolos-gelados-diamante-negro', 'Diamante Negro', 'Bolos Gelados', 66),
  ('p-bolos-gelados-doce-de-leite-c-ninho', 'Doce de Leite c/ Ninho', 'Bolos Gelados', 70),
  ('p-bolos-gelados-mineirinha', 'Mineirinha', 'Bolos Gelados', 36),
  ('p-bolos-gelados-torta-pistache', 'Torta Pistache', 'Bolos Gelados', 0),
  ('p-bolos-gelados-pave-de-nozes', 'Pavê de Nozes', 'Bolos Gelados', 31),
  ('p-bolos-gelados-pave-laka-oreo', 'Pavê Laka Oreo', 'Bolos Gelados', 33),
  ('p-bolos-gelados-prestigio', 'Prestígio', 'Bolos Gelados', 52),
  ('p-bolos-gelados-torta-de-pistache-c-limao', 'Torta de pistache c/ limão', 'Bolos Gelados', 37),
  ('p-bolos-gelados-torta-kinder', 'Torta Kinder', 'Bolos Gelados', 73),
  ('p-bolos-de-potes-pistache', 'Pistache', 'Bolos de Potes', 10),
  ('p-bolos-de-potes-pacoca', 'Paçoca', 'Bolos de Potes', 44),
  ('p-bolos-de-potes-shot', 'Shot', 'Bolos de Potes', 2),
  ('p-bolos-de-potes-maracuja-c-chocolate', 'Maracujá c/ Chocolate', 'Bolos de Potes', 0),
  ('p-bolos-de-potes-ninho-trufado-c-morango', 'Ninho Trufado c/ Morango', 'Bolos de Potes', 0),
  ('p-bolos-de-potes-quatro-leites', 'Quatro Leites', 'Bolos de Potes', 79),
  ('p-bolos-de-potes-red-velvet', 'Red Velvet', 'Bolos de Potes', 10),
  ('p-bolos-de-potes-alpino', 'Alpino', 'Bolos de Potes', 45),
  ('p-congelados-cookies-cenoura-c-chocolate', 'Cookies Cenoura c/ Chocolate', 'Congelados', 0),
  ('p-congelados-cookies-nutella', 'Cookies Nutella', 'Congelados', 51),
  ('p-congelados-cookies-bueno', 'Cookies Bueno', 'Congelados', 39),
  ('p-congelados-ciabatta-pct-c-5-und', 'Ciabatta Pct c/ 5 und', 'Congelados', 2),
  ('p-congelados-croissant-und', 'Croissant und', 'Congelados', 9),
  ('p-congelados-pao-de-queijo-pct', 'Pão de Queijo Pct', 'Congelados', 0),
  ('p-congelados-empadao-carne-p', 'Empadão Carne P', 'Congelados', 82),
  ('p-congelados-empadao-camarao-p', 'Empadão Camarão P', 'Congelados', 225),
  ('p-congelados-empadao-frango-c-requeijao-p', 'Empadão Frango c/ Requeijão P', 'Congelados', 110),
  ('p-congelados-empadao-frango-s-requeijao-p', 'Empadão Frango s/ Requeijão P', 'Congelados', 0),
  ('p-congelados-empadao-frango-c-palmito-cremoso-p', 'Empadão Frango c/ Palmito Cremoso P', 'Congelados', 33),
  ('p-congelados-empadao-file-4-queijos-p', 'Empadão Filé 4 Queijos P', 'Congelados', 20),
  ('p-congelados-empadao-palmito-cremoso-p', 'Empadão Palmito Cremoso P', 'Congelados', 80),
  ('p-congelados-empadao-carne-1kg', 'Empadão Carne 1kg', 'Congelados', 2),
  ('p-congelados-empadao-camarao-1kg', 'Empadão Camarão 1kg', 'Congelados', 1),
  ('p-congelados-empadao-frango-c-requeijao-1kg', 'Empadão Frango c/ Requeijão 1kg', 'Congelados', 2),
  ('p-congelados-empadao-frango-c-palmito-1kg', 'Empadão Frango c/ Palmito 1kg', 'Congelados', 0),
  ('p-congelados-empadao-file-4-queijos-1kg', 'Empadão Filé 4 Queijos 1kg', 'Congelados', 1),
  ('p-congelados-empadao-palmito-cremoso-1kg', 'Empadão Palmito Cremoso 1kg', 'Congelados', 0),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-pudim-vitrine', 'Torta de acrílico pudim (vitrine)', 'Tortas Acrílico Fatia', 3),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-morango-c-suspiro-vitrine', 'Torta de acrílico Morango c/ suspiro (vitrine)', 'Tortas Acrílico Fatia', 0),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-morango-cravejado-vitrine', 'Torta de acrílico Morango cravejado (vitrine)', 'Tortas Acrílico Fatia', 0),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-prestigio-vitrine', 'Torta de acrílico Prestígio (vitrine)', 'Tortas Acrílico Fatia', 0),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-bem-casado-vitrine', 'Torta de acrílico Bem casado (vitrine)', 'Tortas Acrílico Fatia', 3),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-marta-rocha-vitrine', 'Torta de acrílico Marta Rocha (vitrine)', 'Tortas Acrílico Fatia', 0),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-maracuja-com-chocolate-vitrine', 'Torta de acrílico Maracujá com chocolate (vitrine)', 'Tortas Acrílico Fatia', 0),
  ('p-tortas-acrilico-fatia-torta-de-acrilico-pistache-c-chocolate-vitrine', 'Torta de acrílico pistache c/ chocolate (vitrine)', 'Tortas Acrílico Fatia', 0),
  ('p-encomendas-docinho-ninho-c-nutella-und', 'Docinho ninho c/ nutella und', 'Encomendas', 0),
  ('p-encomendas-mini-brownie-stikadinho-und', 'Mini brownie stikadinho und', 'Encomendas', 0),
  ('p-encomendas-caseirinho-de-cenoura-g', 'Caseirinho de cenoura G', 'Encomendas', 0),
  ('p-encomendas-caseirinho-nutelinho-g-sem-cobertura', 'Caseirinho nutelinho G (sem cobertura)', 'Encomendas', 0)
on conflict (id) do nothing;
